# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/wolf/fpga/u55c_pcie_template/project.runs/top_level_axil_slave_0_0_synth_1/top_level_axil_slave_0_0.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "top_level_axil_slave_0_0_synth_1" START { ROLLUP_AUTO }
set_param bd.open.in_stealth_mode 1
set_msg_config  -id {Vivado 12-1790}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {BD 41-927}  -suppress 
set_msg_config  -id {Synth 8-7129}  -suppress 
set_msg_config  -id {Synth 8-7071}  -suppress 
set_msg_config  -id {Synth 8-7080}  -suppress 
set_msg_config  -id {DRC PLCK-58}  -string {{WARNING: [DRC PLCK-58] Clock Placer Checks: Sub-optimal placement for a global clock-capable IO pin and BUFG pair.
Resolution: A dedicated routing path between the two can be used if: (a) The global clock-capable IO (GCIO) is placed on a GCIO capable site (b) The BUFG is placed in the same bank of the device as the GCIO pin. Both the above conditions must be met at the same time, else it may lead to longer and less predictable clock insertion delays.
 This is normally an ERROR but the CLOCK_DEDICATED_ROUTE constraint is set to FALSE allowing your design to continue. The use of this override is highly discouraged as it may lead to very poor timing results. It is recommended that this error condition be corrected in the design.

	init_clk_IBUF_inst/IBUFCTRL_INST (IBUFCTRL.O) is locked to IOB_X1Y101
	init_clk_IBUF_BUFG_inst (BUFGCE.I) is provisionally placed by clockplacer on BUFGCE_X1Y28}}  -suppress 
set_msg_config  -id {DRC RTSTAT-10}  -string {{WARNING: [DRC RTSTAT-10] No routable loads: 355 net(s) have no routable loads. The problem bus(es) and/or net(s) are top_level_i/packet_buffer/channel_0/ddr/ddr4/inst/u_ddr4_mem_intfc/u_ddr_cal_riu/LMB_CE_riu, top_level_i/packet_buffer/channel_1/ddr/ddr4/inst/u_ddr4_mem_intfc/u_ddr_cal_riu/LMB_CE_riu, top_level_i/packet_buffer/channel_1/ddr/ddr4/inst/u_ddr4_mem_intfc/u_ddr_cal_riu/LMB_UE_riu, top_level_i/packet_buffer/channel_0/ddr/ddr4/inst/u_ddr4_mem_intfc/u_ddr_cal_riu/LMB_UE_riu, top_level_i/packet_buffer/channel_0/ddr/ddr4/inst/u_ddr4_mem_intfc/u_ddr_cal_top/u_ddr_cal/u_xsdb_arbiter/Q[12], top_level_i/packet_buffer/channel_1/ddr/ddr4/inst/u_ddr4_mem_intfc/u_ddr_cal_top/u_ddr_cal/u_xsdb_arbiter/Q[12], top_level_i/packet_buffer/channel_1/ddr/ddr4/inst/u_ddr4_mem_intfc/u_ddr_cal_top/u_ddr_cal/u_xsdb_arbiter/Q[13], top_level_i/packet_buffer/channel_0/ddr/ddr4/inst/u_ddr4_mem_intfc/u_ddr_cal_top/u_ddr_cal/u_xsdb_arbiter/Q[13], top_level_i/packet_buffer/channel_0/ddr/ddr4/inst/u_ddr4_mem_intfc/u_ddr_cal_top/u_ddr_cal/u_xsdb_arbiter/Q[14], top_level_i/packet_buffer/channel_1/ddr/ddr4/inst/u_ddr4_mem_intfc/u_ddr_cal_top/u_ddr_cal/u_xsdb_arbiter/Q[14], top_level_i/packet_buffer/channel_1/ddr/ddr4/inst/u_ddr4_mem_intfc/u_ddr_cal_top/u_ddr_cal/u_xsdb_arbiter/Q[15], top_level_i/packet_buffer/channel_0/ddr/ddr4/inst/u_ddr4_mem_intfc/u_ddr_cal_top/u_ddr_cal/u_xsdb_arbiter/Q[15], top_level_i/packet_buffer/channel_1/ddr/ddr4/inst/u_ddr4_mem_intfc/u_phy2clb_fixdly_rdy_upp/SYNC[0].sync_reg[1], top_level_i/packet_buffer/channel_1/ddr/ddr4/inst/u_ddr4_mem_intfc/u_phy2clb_fixdly_rdy_low/SYNC[0].sync_reg[1], top_level_i/packet_buffer/channel_0/ddr/ddr4/inst/u_ddr4_mem_intfc/u_phy2clb_fixdly_rdy_upp/SYNC[0].sync_reg[1]... and (the first 15 of 313 listed).}}  -suppress 
set_msg_config  -id {DRC REQP-1858}  -string {{WARNING: [DRC REQP-1858] RAMB36E2_writefirst_collision_advisory: Synchronous clocking is detected for BRAM (top_level_i/pcie_bridge/pcie_bridge/inst/pcie4_ip_i/inst/top_level_xdma_0_0_pcie4_ip_pcie_4_0_pipe_inst/pcie_4_0_bram_inst/RAM32K.bram_comp_inst/bram_16k_0_int/ECC_RAM.RAMB36E2[0].ramb36e2_inst) in SDP mode with WRITE_FIRST write-mode. It is strongly suggested to change this mode to NO_CHANGE for best power characteristics. However, both WRITE_FIRST and NO_CHANGE may exhibit address collisions if the same address appears on both read and write ports resulting in unknown or corrupted read data. It is suggested to confirm via simulation that an address collision never occurs and if so it is suggested to try and avoid this situation. If address collisions cannot be avoided, the write-mode may be set to READ_FIRST which guarantees that the read data is the prior contents of the memory at the cost of additional power in the design. See the FPGA Memory Resources User Guide for additional information.}}  -suppress 
set_msg_config  -id {Netlist 29-101}  -suppress 
set_msg_config  -id {BD 41-927}  -string {{WARNING: [BD 41-927] Following properties on pin /channel_0/packet_buffer/data_buffer/ram/hbm_0/AXI_00_ACLK have been updated from connected ip, but BD cell '/channel_0/packet_buffer/data_buffer/ram/hbm_0' does not accept parameter changes, so they may not be synchronized with cell properties:
	FREQ_HZ = 250000000 
Please resolve any mismatches by directly setting properties on BD cell </channel_0/packet_buffer/data_buffer/ram/hbm_0> to completely resolve these warnings.}}  -suppress 
set_msg_config  -id {DRC REQP-1858}  -suppress 
set_msg_config  -id {DRC PDCN-1569}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_param project.vivado.isBlockSynthRun true
OPTRACE "Creating in-memory project" START { }
set_param ips.modRefOverrideMrefDirPath /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/mref
create_project -in_memory -part xcu55c-fsvh2892-2L-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/wolf/fpga/u55c_pcie_template/project.cache/wt [current_project]
set_property parent.project_path /home/wolf/fpga/u55c_pcie_template/project.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
update_ip_catalog
set_property ip_output_repo /home/wolf/fpga/u55c_pcie_template/project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  /home/wolf/fpga/u55c_pcie_template/src/common/axi4_lite_slave.v
  /home/wolf/fpga/u55c_pcie_template/src/axil_slave.v
}
read_ip -quiet /home/wolf/fpga/u55c_pcie_template/project.srcs/sources_1/bd/top_level/ip/top_level_axil_slave_0_0/top_level_axil_slave_0_0.xci

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top_level_axil_slave_0_0 -part xcu55c-fsvh2892-2L-e -incremental_mode off -mode out_of_context
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}

rename_ref -prefix_all top_level_axil_slave_0_0_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_level_axil_slave_0_0.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file top_level_axil_slave_0_0_utilization_synth.rpt -pb top_level_axil_slave_0_0_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force /home/wolf/fpga/u55c_pcie_template/project.runs/top_level_axil_slave_0_0_synth_1/top_level_axil_slave_0_0.dcp /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_axil_slave_0_0/top_level_axil_slave_0_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_axil_slave_0_0/top_level_axil_slave_0_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_axil_slave_0_0/top_level_axil_slave_0_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_axil_slave_0_0/top_level_axil_slave_0_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_axil_slave_0_0/top_level_axil_slave_0_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/wolf/fpga/u55c_pcie_template/project.ip_user_files/ip/top_level_axil_slave_0_0]} {
  catch { 
    file copy -force /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_axil_slave_0_0/top_level_axil_slave_0_0_stub.v /home/wolf/fpga/u55c_pcie_template/project.ip_user_files/ip/top_level_axil_slave_0_0
  }
}

if {[file isdir /home/wolf/fpga/u55c_pcie_template/project.ip_user_files/ip/top_level_axil_slave_0_0]} {
  catch { 
    file copy -force /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_axil_slave_0_0/top_level_axil_slave_0_0_stub.vhdl /home/wolf/fpga/u55c_pcie_template/project.ip_user_files/ip/top_level_axil_slave_0_0
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "top_level_axil_slave_0_0_synth_1" END { }
