# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/wolf/fpga/u55c_pcie_template/xdc/board.xdc

# Block Designs: bd/top_level/top_level.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level || ORIG_REF_NAME==top_level} -quiet] -quiet

# IP: bd/top_level/ip/top_level_xdma_0_0/top_level_xdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_xdma_0_0 || ORIG_REF_NAME==top_level_xdma_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_util_ds_buf_0_0/top_level_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_util_ds_buf_0_0 || ORIG_REF_NAME==top_level_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_smartconnect_0_0/top_level_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_smartconnect_0_0 || ORIG_REF_NAME==top_level_smartconnect_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_xlconstant_0_0/top_level_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_xlconstant_0_0 || ORIG_REF_NAME==top_level_xlconstant_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axil_slave_0_0/top_level_axil_slave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axil_slave_0_0 || ORIG_REF_NAME==top_level_axil_slave_0_0} -quiet] -quiet

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/top_level_ooc.xdc
