# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wolf/fpga/u55c_pcie_template/project.srcs/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/top_level_smartconnect_0_0.xci
# IP: The module: 'top_level_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/bd_f519.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_0/bd_f519_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_1/bd_f519_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_2/bd_f519_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_3/bd_f519_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_4/bd_f519_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_5/bd_f519_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_6/bd_f519_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_7/bd_f519_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_8/bd_f519_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_9/bd_f519_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_10/bd_f519_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_11/bd_f519_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_12/bd_f519_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_1/bd_f519_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_1/bd_f519_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_5/bd_f519_s00a2s_0_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_6/bd_f519_sarn_0_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_7/bd_f519_srn_0_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_8/bd_f519_sawn_0_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_9/bd_f519_swn_0_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_10/bd_f519_sbn_0_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_11/bd_f519_m00s2a_0_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/wolf/fpga/u55c_pcie_template/project.srcs/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/top_level_smartconnect_0_0.xci
# IP: The module: 'top_level_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/bd_f519.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_0/bd_f519_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_1/bd_f519_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_2/bd_f519_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_3/bd_f519_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_4/bd_f519_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_5/bd_f519_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_6/bd_f519_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_7/bd_f519_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_8/bd_f519_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_9/bd_f519_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_10/bd_f519_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_11/bd_f519_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_12/bd_f519_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_1/bd_f519_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_1/bd_f519_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_5/bd_f519_s00a2s_0_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_6/bd_f519_sarn_0_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_7/bd_f519_srn_0_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_8/bd_f519_sawn_0_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_9/bd_f519_swn_0_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_10/bd_f519_sbn_0_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_11/bd_f519_m00s2a_0_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
