# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wolf/fpga/u55c_pcie_template/project.srcs/sources_1/bd/top_level/ip/top_level_util_ds_buf_0_0/top_level_util_ds_buf_0_0.xci
# IP: The module: 'top_level_util_ds_buf_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_util_ds_buf_0_0/top_level_util_ds_buf_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_util_ds_buf_0_0/top_level_util_ds_buf_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/wolf/fpga/u55c_pcie_template/project.srcs/sources_1/bd/top_level/ip/top_level_util_ds_buf_0_0/top_level_util_ds_buf_0_0.xci
# IP: The module: 'top_level_util_ds_buf_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_util_ds_buf_0_0/top_level_util_ds_buf_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_util_ds_buf_0_0/top_level_util_ds_buf_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
