# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wolf/fpga/u55c_pcie_template/project.srcs/sources_1/bd/top_level/ip/top_level_xdma_0_0/top_level_xdma_0_0.xci
# IP: The module: 'top_level_xdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_2/xdma_v4_1_31_blk_mem_64_noreg_be.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_31_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_1_31_blk_mem_64_noreg_be} -quiet] -quiet

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_1/xdma_v4_1_31_blk_mem_64_reg_be.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_31_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_1_31_blk_mem_64_reg_be} -quiet] -quiet

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_0/top_level_xdma_0_0_pcie4c_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_xdma_0_0_pcie4c_ip || ORIG_REF_NAME==top_level_xdma_0_0_pcie4c_ip} -quiet] -quiet

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_0/ip_0/top_level_xdma_0_0_pcie4c_ip_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_xdma_0_0_pcie4c_ip_gt || ORIG_REF_NAME==top_level_xdma_0_0_pcie4c_ip_gt} -quiet] -quiet

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_2/xdma_v4_1_31_blk_mem_64_noreg_be_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_1/xdma_v4_1_31_blk_mem_64_reg_be_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_0/ip_0/synth/top_level_xdma_0_0_pcie4c_ip_gt_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_0/ip_0/synth/top_level_xdma_0_0_pcie4c_ip_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_level_xdma_0_0_pcie4c_ip_gt || ORIG_REF_NAME==top_level_xdma_0_0_pcie4c_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_0/top_level_xdma_0_0_pcie4c_ip_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_level_xdma_0_0_pcie4c_ip || ORIG_REF_NAME==top_level_xdma_0_0_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_0/source/ip_pcie4c_uscale_plus_impl_x1y1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_level_xdma_0_0_pcie4c_ip || ORIG_REF_NAME==top_level_xdma_0_0_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_0/synth/top_level_xdma_0_0_pcie4c_ip_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_0/synth/top_level_xdma_0_0_pcie4c_ip_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_level_xdma_0_0_pcie4c_ip || ORIG_REF_NAME==top_level_xdma_0_0_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_0/source/ip_pcie4c_uscale_plus_x1y1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_level_xdma_0_0_pcie4c_ip || ORIG_REF_NAME==top_level_xdma_0_0_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/top_level_xdma_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_xdma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/source/top_level_xdma_0_0_pcie4_uscaleplus_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_xdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/synth/top_level_xdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_xdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/wolf/fpga/u55c_pcie_template/project.srcs/sources_1/bd/top_level/ip/top_level_xdma_0_0/top_level_xdma_0_0.xci
# IP: The module: 'top_level_xdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_2/xdma_v4_1_31_blk_mem_64_noreg_be.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_31_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_1_31_blk_mem_64_noreg_be} -quiet] -quiet

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_1/xdma_v4_1_31_blk_mem_64_reg_be.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_31_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_1_31_blk_mem_64_reg_be} -quiet] -quiet

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_0/top_level_xdma_0_0_pcie4c_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_xdma_0_0_pcie4c_ip || ORIG_REF_NAME==top_level_xdma_0_0_pcie4c_ip} -quiet] -quiet

# IP: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_0/ip_0/top_level_xdma_0_0_pcie4c_ip_gt.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_xdma_0_0_pcie4c_ip_gt || ORIG_REF_NAME==top_level_xdma_0_0_pcie4c_ip_gt} -quiet] -quiet

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_2/xdma_v4_1_31_blk_mem_64_noreg_be_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_1/xdma_v4_1_31_blk_mem_64_reg_be_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_0/ip_0/synth/top_level_xdma_0_0_pcie4c_ip_gt_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_0/ip_0/synth/top_level_xdma_0_0_pcie4c_ip_gt.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_level_xdma_0_0_pcie4c_ip_gt || ORIG_REF_NAME==top_level_xdma_0_0_pcie4c_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_0/top_level_xdma_0_0_pcie4c_ip_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_level_xdma_0_0_pcie4c_ip || ORIG_REF_NAME==top_level_xdma_0_0_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_0/source/ip_pcie4c_uscale_plus_impl_x1y1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_level_xdma_0_0_pcie4c_ip || ORIG_REF_NAME==top_level_xdma_0_0_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_0/synth/top_level_xdma_0_0_pcie4c_ip_ooc.xdc

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_0/synth/top_level_xdma_0_0_pcie4c_ip_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_level_xdma_0_0_pcie4c_ip || ORIG_REF_NAME==top_level_xdma_0_0_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/ip_0/source/ip_pcie4c_uscale_plus_x1y1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_level_xdma_0_0_pcie4c_ip || ORIG_REF_NAME==top_level_xdma_0_0_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/top_level_xdma_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_xdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/source/top_level_xdma_0_0_pcie4_uscaleplus_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_xdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wolf/fpga/u55c_pcie_template/project.gen/sources_1/bd/top_level/ip/top_level_xdma_0_0/synth/top_level_xdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_xdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
